parameters:
  - name: configDir
    type: string
    default: ".chglog/config.yml"

  - name: output
    type: string
    default: "CHANGELOG.md"

  - name: useNextTag
    type: boolean
    default: false

  - name: nextTag
    type: string
    default: ""

steps:
  - task: Bash@3
    displayName: "Generate Changelog without --next-tag"
    condition: and(succeeded(), eq('${{ parameters.useNextTag }}', false))
    inputs:
      targetType: 'inline'
      script: |
        set -eu
        git-chglog -c "${CONFIG_DIR}" -o "${OUTPUT}"
    env:
      CONFIG_DIR: ${{ parameters.configDir }}
      OUTPUT: ${{ parameters.output }}

  - task: Bash@3
    displayName: "Generate Changelog with --next-tag"
    condition: and(succeeded(), eq('${{ parameters.useNextTag }}', true))
    inputs:
      targetType: 'inline'
      script: |
        set -eu
        git-chglog -c "${CONFIG_DIR}" --next-tag "${NEXT_TAG}" -o "${OUTPUT}"
    env:
      CONFIG_DIR: ${{ parameters.configDir }}
      NEXT_TAG: ${{ parameters.nextTag }}
      OUTPUT: ${{ parameters.output }}

  - task: Bash@3
    displayName: "Commit changes"
    inputs:
      targetType: 'inline'
      script: |
        set -eu
        git add ${OUTPUT}
        git commit -m "Auto generated CHANGELOG"
        git push -u origin ${BRANCH}
    env:
      OUTPUT: ${{ parameters.output }}
      BRANCH: $(Build.SourceBranchName)
